### ISSUE TITLE
刚下的最新版..点击组件就是空白

### ISSUE THREAD

**Issue by colder112** [alibaba/flutter-go#10]
项目文件列表中爆红,但是点进文件里没有报错.可以运行,就是组件这个页面时空白
1.0.0
dark: 2.1.0-dev.94

**Comment by Nealyang** [comment]
代码已更新

**Comment by gitKun** [comment]
太偏安卓风格了 不太喜欢

**Comment by hanxu317317** [comment]
@gitKun 亲, 这个版本的效果是偏android,  flutter本身支持ios效果.  未来我们会入上的.
