### ISSUE TITLE
CupertinoColors.darkBackgroundGray找不到

### ISSUE THREAD

**Issue by unreal0** [alibaba/flutter-go#101]
CupertinoColors.darkBackgroundGray提示没有定义

**Comment by KangGuiYang** [comment]
+1

**Comment by hanxu317317** [comment]
flutter upgrade.  请升级flutter 包.

**Comment by FindMeXY** [comment]
已经升级成功了，但是还是报错
![image](https://user-images.githubusercontent.com/7193615/52030635-b0c93380-2553-11e9-8413-260891a01dab.png)

**Comment by Clancyin** [comment]
我也是这里编译过不去

**Comment by hanxu317317** [comment]
#107 @Clancyin @FindMeXY @KangGuiYang @unreal0 具体已经在这个issue中解决. 大家看一下.
