### ISSUE TITLE
demo跑不起来

### ISSUE THREAD

**Issue by 17671621757** [alibaba/flutter-go#102]
/bin/sh: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory

**Comment by hanxu317317** [comment]
it looks like https://github.com/flutter/flutter/issues/26878.

**Comment by Olayemi12** [comment]
Hello am new here how it works

**Comment by hanxu317317** [comment]
> Hello am new here how it works
@Olayemi12 

```
git clone git@github.com:alibaba/flutter-go.git

cd flutter-go

flutter packages get

flutter run 

```
