### ISSUE TITLE
缺失组件”CupertinoTheme“，"Brightness".尝试搜索引用未果

### ISSUE THREAD

**Issue by phantomr2** [alibaba/flutter-go#107]
error: Undefined name 'CupertinoTheme'. (undefined_identifier at [flutter_go] lib\widgets\themes\Cupertino\CupertinoPicker\demo.dart:50)
error: Undefined name 'CupertinoTheme'. (undefined_identifier at [flutter_go] lib\widgets\themes\Cupertino\CupertinoPicker\demo.dart:268)
error: Undefined name 'CupertinoTheme'. (undefined_identifier at [flutter_go] lib\widgets\themes\Cupertino\CupertinoPicker\demo.dart:271)
error: Undefined name 'Brightness'. (undefined_identifier at [flutter_go] lib\widgets\themes\Cupertino\CupertinoPicker\demo.dart:271)

**Comment by hanxu317317** [comment]
it looks liek #101

**Comment by CrazyCoderShi** [comment]
这里友情提示一下，Brightness在appbar上控制状态条的颜色，特别好事

**Comment by hanxu317317** [comment]
小哥, 提示的特别带劲.

**Comment by hanxu317317** [comment]
@phantomr2 您那边解决这个问题了么?

**Comment by somebugs** [comment]
`CupertinoTheme` 是 `flutter 1.1.3`加入的新特性，需要更新到以上的版本。详见
[Flutter Changelog](https://github.com/flutter/flutter/wiki/Changelog)

**Comment by hanxu317317** [comment]
我们的flutter版本一直在追新. 没考虑到大家安装的是1.0的flutter, 我们已经把新特性,去掉了. 大家可以拉取最新develop
@phantomr2

**Comment by CrazyCoderShi** [comment]
@phantomr2 我觉得可以在README里面标明这些，不然可能后续还是有人来问这个问题，不如一次性在根源上解决掉

**Comment by DeckeDeng** [comment]
> @phantomr2 我觉得可以在README里面标明这些，不然可能后续还是有人来问这个问题，不如一次性在根源上解决掉

是的，我们也注意到版本问题了，现在已经在考虑各种方案中～希望找到一个最好的解决办法

**Comment by phantomr2** [comment]
flutter 更新到dev最新版后这个问题解决。

**Comment by zengyuangai** [comment]
@phantomr2  已经上最新的dev了 还是不行

**Comment by zengyuangai** [comment]
@hanxu317317  可以了 感恩～

**Comment by hanxu317317** [comment]
@zengyuangai 兄弟, 过年没事无聊, 学习写代码啊, 这是
