### ISSUE TITLE
想问一下pubspec.yaml文件中的    - lib/utils/example_code_parser.dart     - lib/utils/syntax_highlighter.dart是干什么的？

### ISSUE THREAD

**Issue by gejiashu** [alibaba/flutter-go#108]
里面的demo.dart是用来把源文件打包到apk的，然后在Example_Code界面展示的，但是这两个我看了项目的代码好用没用到这两个源文件，不知道这两个的用途？

**Comment by hanxu317317** [comment]
@gejiashu 
syntax_highlighter: 是为了支持官方的markdown, 不支持代码高亮的扩展组件, 二期准备使用.
example_code_parser: 用来在手机上显示demo的代码

**Comment by gejiashu** [comment]
这个两个文件的作用我知道，我的意思是为什么要配置在pubspec.yaml中间中?

![image](https://user-images.githubusercontent.com/7670817/52027367-20d0bd00-2546-11e9-852e-9d1860596668.png)

**Comment by Nealyang** [comment]
> 这个两个文件的作用我知道，我的意思是为什么要配置在pubspec.yaml文件中?
> 
> ![image](https://user-images.githubusercontent.com/7670817/52027367-20d0bd00-2546-11e9-852e-9d1860596668.png)

pubspec.yaml 文件中的确没有必要加这两个文件，当时为了写读取文件测试加进来的，后来忘记删了，已删除目前。感谢指出。

**Comment by hanxu317317** [comment]
在这个里边. 的确是没什么用.  可以无视. 我们尽快删掉.

**Comment by gejiashu** [comment]
@Nealyang 好的 谢谢
