### ISSUE TITLE
一堆大小写错误，导致编译失败

### ISSUE THREAD

**Issue by jiangkang** [alibaba/flutter-go#11]
路径名，文件名拼写与引入的大小写不对应，导致编译失败
![image](https://user-images.githubusercontent.com/12570868/50947056-6e25b580-14d7-11e9-8669-0bb50af5b217.png)

**Comment by champkeh** [comment]
<img width="915" alt="wx20190110-131019 2x" src="https://user-images.githubusercontent.com/7316006/50947437-4e8f8c80-14d9-11e9-8c16-dda46527ab8a.png">

还有就是很多组件都有必需参数，但demo里面都不填，导致报错

**Comment by champkeh** [comment]
<img width="836" alt="wx20190110-131524 2x" src="https://user-images.githubusercontent.com/7316006/50947547-d37aa600-14d9-11e9-8bb6-dce64fdfab25.png">

**Comment by hanxu317317** [comment]
有部份组件, 后来替代重构. 有些地方还没有改全.   我们接下来会整理这些问题

**Comment by hanxu317317** [comment]
小哥~我们已经规范了大部份代码. 感谢您的建议.

**Comment by zhaokidd** [comment]
+1 大小写问题导致import失败，最新代码里还是有这个问题啊。这种错误希望还是注意下，尽可能避免。
