### ISSUE TITLE
Android studio跑不起来

### ISSUE THREAD

**Issue by CLOUD-wuzichen** [alibaba/flutter-go#127]
下载后配置了dart sdk目录和futter目录、依赖包下载后，项目编译通过，但是不管是接上模拟器还是真机都跑步起来，
![image](https://user-images.githubusercontent.com/30900888/52680220-aa36b500-2f72-11e9-85f1-200fc9798f84.png)
![image](https://user-images.githubusercontent.com/30900888/52680232-b3c01d00-2f72-11e9-8e3e-1b00d517f193.png)
编译时候出现以下信息后就停了，message和event log都没有啥信息，想问问是怎么回事？谢谢
![image](https://user-images.githubusercontent.com/30900888/52680241-be7ab200-2f72-11e9-9f42-5f357a913c37.png)
![image](https://user-images.githubusercontent.com/30900888/52680265-d05c5500-2f72-11e9-9d74-d4e17574ea18.png)

**Comment by champkeh** [comment]
是不是墙的原因？依赖下载不下来

**Comment by CLOUD-wuzichen** [comment]
> 是不是墙的原因？依赖下载不下来

不是的 我自己建的项目也有依赖 可以跑起来，demo不行，demo编译一会就自动断了，没有任何报错，如果是依赖错误一开始就编译不过了 我也纳闷啊

**Comment by champkeh** [comment]
我刚试了下，这两步会久一点，我等了5、6分钟，之后就过了 编译没有断
你说的编译中断的情况，我就不知道 了

**Comment by hanxu317317** [comment]
就是科学主义墙体的问题~~~

**Comment by hanxu317317** [comment]
如果无梯子. 参考一下这个.

> 既然是中文学习为主了， `android/build.gradle` 中的 repositories 改为用 aliyun 的 maven 源应该更好一些。不然不开科学上网则 android 构建默认会卡在 `Resolving dependencies...`。
> 
> 参考：
> 
> ```js
> buildscript {
>     repositories {
>         maven { url 'https://maven.aliyun.com/repository/google' }
>         maven { url 'https://maven.aliyun.com/repository/jcenter' }
>         maven { url 'https://maven.aliyun.com/repository/public' }
>         maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
>         google()
>         jcenter()
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.2.1'
>     }
> }
> 
> allprojects {
>     repositories {
>         maven { url 'https://maven.aliyun.com/repository/google' }
>         maven { url 'https://maven.aliyun.com/repository/jcenter' }
>         maven { url 'https://maven.aliyun.com/repository/public' }
>         maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
>         google()
>         jcenter()
>     }
> }
> 
> rootProject.buildDir = '../build'
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
>     project.evaluationDependsOn(':app')
> }
> 
> task clean(type: Delete) {
>     delete rootProject.buildDir
> }
> ```
