### ISSUE TITLE
Windows环境下，androidStudio在真机上运行出现异常

### ISSUE THREAD

**Issue by 603751448** [alibaba/flutter-go#131]
Windows环境下，androidStudio在真机上运行出现异常。
荣耀5X，6.0.1。

**Comment by 603751448** [comment]
flutter-go-master\lib\views\fourth_page\pager_indicator.dart
63 行，int类型不能转化为double类型
transform: new Matrix4.translationValues(0, 0.0, 0.0)   // 源代码
transform: new Matrix4.translationValues(0.0, 0.0, 0.0)   // 修改后

不知道为什么我的会在这里报错，你们的都没有问题吗 ？

**Comment by hanxu317317** [comment]
目前没有收到这种报错信息. doctor一下. 看看你本地的版本信息.

**Comment by 603751448** [comment]
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.472], locale zh-CN)
    • Flutter version 0.9.4 at D:\aFlutter\flutter
    • Framework revision f37c235c32 (5 months ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

**Comment by hanxu317317** [comment]
本项目环境持续更新. 请定期更新各依赖包.
dart(version: 2.0.0)
flutter(version: v1.0.0)

早期的flutter包 对于数字 1 与1.0的处理是不同的.
@603751448
