### ISSUE TITLE
来回切换tab，重新绘制页面

### ISSUE THREAD

**Issue by ChenPanPan0629** [alibaba/flutter-go#14]
来回切换tab，不想重新绘制页面，如何保持页面状态呢

**Comment by insrv** [comment]
> 来回切换tab，不想重新绘制页面，如何保持页面状态呢

你可以先把tab页面new出来然后放到一个List中，使页面根据现在选中的activeIndex来显示List中的某一个tab页，然后setState改变控制tab页面显示的activeIndex

**Comment by hanxu317317** [comment]
使用IndexedStack去存放tabList, 也是可以做到的.  使用方法参考[IndexedStack](https://docs.flutter.io/flutter/widgets/IndexedStack-class.html)

**Comment by Nealyang** [comment]
@ChenPanPan0629  develop分支代码已更新，避免重绘

**Comment by ryan730** [comment]
两种方案：
https://www.jianshu.com/p/b95ff1e2ab00
