### ISSUE TITLE
上拉加载的疑惑

### ISSUE THREAD

**Issue by zhaoweiguo5505** [alibaba/flutter-go#153]
flutter里面是没有上拉加载的widget，你们目前做的是判断index是否等于item.length。但是如果item数量没有占满整个屏幕，额外加载的widget还会显示吧？

**Comment by zhaoweiguo5505** [comment]
对，如果item没有占满屏幕，最下面的下拉加载还是会显示吧。

**Comment by zhaoweiguo5505** [comment]
if (index == items.length) {
            //return _buildLoadText();
            return _buildProgressIndicator();
          } 
当前判断如果index ==items.length，就加载最下面的加载更多，但是如果list并没有占满屏幕，那最下面的加载更多还会显示的吧？

**Comment by hanxu317317** [comment]
应该是这样的. 这算是一种极端情况 , 
底部的widget应该动态判断一下.
