### ISSUE TITLE
关于部分代码文件夹的问题

### ISSUE THREAD

**Issue by CaiJingLong** [alibaba/flutter-go#155]
![image](https://user-images.githubusercontent.com/14145407/53080547-e26e6280-3533-11e9-917e-cc121be64e4d.png)

如图所示,还是建议有时间重新整理下所有文件夹,以保证符合规范

**Comment by hanxu317317** [comment]
这部份的文件命名. 我们是以组件名命名. 保留大写.

**Comment by CaiJingLong** [comment]
了解了


在2019年02月20日 17:22，hanxu317317<notifications@github.com> 写道：

这部份的文件命名. 我们是以组件名命名. 保留大写.
