### ISSUE TITLE
iOS界面跳转问题

### ISSUE THREAD

**Issue by ZGYManggo** [alibaba/flutter-go#156]
初上手这个项目，在真机测试的时候发现界面呈现方式都是通过present的方式，flutter没有Navigation的push方式吗？感觉操作上很不友好

**Comment by Nealyang** [comment]
目前呈现的方式很类似iOS中present方式，当然，我们正在考虑是否需要修改路由跳转方式，但是在Flutter中，路由跳转方式都是可以配置的。Android和iOS上区分弹出方式也可以通过设置```fullscreenDialog ```属性
