### ISSUE TITLE
代码开发规范 0.1.0 版中库的引用与 Dart 官方规范有区别，有点迷茫到底该采用哪一种

### ISSUE THREAD

**Issue by cv0cv0** [alibaba/flutter-go#157]
如果使用 IDE 提示导入是 package: 开头的，但是官方规范中又规定需要使用相对路径。

**Comment by Nealyang** [comment]
的确在gallery官方demo使用的都是相对路径。但是这里我们采用相对路径和包名结合的形式原因有二：

首先，我们跟进Flutter channel的master分支，也就是最新版本，去年曾发生过相对路build出来报错的情况，但是改为```package:flutter_go```的方式就没有问题。

然后考虑目前我们还未接入后台，组件的详情页非常多，暂时还未归一。层级相对较深。对于common类组件的引入阅读性非常差。

综上，我们综合使用了package的引入方式和相对路径的引入方式。

**Comment by cv0cv0** [comment]
> 的确在gallery官方demo使用的都是相对路径。但是这里我们采用相对路径和包名结合的形式原因有二：
> 
> 首先，我们跟进Flutter channel的master分支，也就是最新版本，去年曾发生过相对路build出来报错的情况，但是改为`package:flutter_go`的方式就没有问题。
> 
> 然后考虑目前我们还未接入后台，组件的详情页非常多，暂时还未归一。层级相对较深。对于common类组件的引入阅读性非常差。
> 
> 综上，我们综合使用了package的引入方式和相对路径的引入方式。

感谢解答。
