### ISSUE TITLE
as配置了flutter 和 dart 运行就一直报错

### ISSUE THREAD

**Issue by chengmenghuiAndroid** [alibaba/flutter-go#158]

**Comment by jhbxyz** [comment]
我也是不知道如何解

**Comment by hanxu317317** [comment]
可以说一下. 报什么错误. 把具体信息发现来. 我们好帮忙看一下. 有时候flutter本身会报一些错误.
@jhbxyz @chengmenghuiAndroid

**Comment by chengmenghuiAndroid** [comment]
非常感谢回复 之前是依赖包没有下载完 后面已经能正常运行




cheng_oop@foxmail.com
 
发件人： JiangHaibo
发送时间： 2019-02-23 17:00
收件人： alibaba/flutter-go
抄送： 程孟辉; Author
主题： Re: [alibaba/flutter-go] as配置了flutter 和 dart 运行就一直报错 (#158)
我也是不知道如何解
―

**Comment by hanxu317317** [comment]
好的. 期待您的反馈.
