### ISSUE TITLE
请问能不能做一个类似朋友圈选择图片的

### ISSUE THREAD

**Issue by SimonHolmeslm** [alibaba/flutter-go#167]
我觉得单选的样式过于简单了.像朋友圈一样选择图片,自定义这个组件会更好.目前我还没能做出来...不知道团队有没有时间或者想法做一个示例呢?

**Comment by hanxu317317** [comment]
这是一个种业务组件的需求. 我们可能不太会费精力去做. 如果您做出来. 可以提pr上来. 我们可以收录进master

**Comment by CrazyCoderShi** [comment]
@SimonHolmeslm 
这种业务组件不应该放这里
[这个东西](https://github.com/Sh1d0w/multi_image_picker)也许能符合你的需求

**Comment by hanxu317317** [comment]
> 这个东西

@CrazyCoderShi 我们最近打算. 把具体组件结合业务, 做一个栏目. 所以是可以收进来的.

**Comment by CrazyCoderShi** [comment]
@hanxu317317 是有打算重开一个 repo ？
