### ISSUE TITLE
建议：建一个flutter开发的微信交流群

### ISSUE THREAD

**Issue by ifrontend-xyz** [alibaba/flutter-go#185]

**Comment by hanxu317317** [comment]
这个建议可以有的. 觉得开一个钉钉群怎么样?

**Comment by ifrontend-xyz** [comment]
可以微信和钉钉都有，大家自由选择

**Comment by wangbaojin2008** [comment]
建议开通微信群

**Comment by shzyxk** [comment]
让阿里的开微信群，你们是不是来捣乱的

**Comment by Gavin-J** [comment]
> 这个建议可以有的. 觉得开一个钉钉群怎么样?

钉钉群更好一些，微信群真心不好用

**Comment by huiming666** [comment]
有钉钉群吗？给个群号

**Comment by Lizhooh** [comment]
哈哈，我还是建议开微信群

**Comment by Revive-Anna** [comment]
那最后到底是开了什么群呢？可以公布一下吗？

**Comment by stylehuan** [comment]
群呢？

**Comment by v3u3i87** [comment]
开个钉钉群吧，方便交流

**Comment by webkonglong** [comment]
群呢？

**Comment by hanxu317317** [comment]
@webkonglong @v3 @st
 @Revive-Anna @Lizhooh @huiming666 @Gavin-J @shzyxk @ifrontend-xyz 

![image](https://user-images.githubusercontent.com/8518989/65209606-4e657900-dacb-11e9-8c9c-01e5f903f5fe.png)

钉钉群 大家可以看一下

**Comment by cdmalcl** [comment]
![WechatIMG737](https://user-images.githubusercontent.com/8749073/72230429-6029d980-35f0-11ea-8d8f-5cb2cae6dcaf.jpeg)
微信群 如果过期了 加我微信就行：cdmalcl
