### ISSUE TITLE
Awesome Flutter

### ISSUE THREAD

**Issue by Solido** [alibaba/flutter-go#19]
你好 ! 
I manage https://github.com/Solido/awesome-flutter (11000 ⭐️)
I'd like to add this app to the best app some more flutter devs can discover it.
Send a Pull Request please !
Regards

**Comment by minghe** [comment]
OK，thx。

**Comment by hanxu317317** [comment]
> 你好 !
> I manage https://github.com/Solido/awesome-flutter (11000 ⭐️)
> I'd like to add this app to the best app some more flutter devs can discover it.
> Send a Pull Request please !
> Regards

I have already sent a pull request [Added "Flutter-Common-Widgets-App" to Open Source Apps Section](https://github.com/Solido/awesome-flutter/pull/290), If there are have any problems please tell me , thank you.

**Comment by Solido** [comment]
Added Thx !
