### ISSUE TITLE
为什么Appstore里面上架的flutter没有留下项目地址和开发信息

### ISSUE THREAD

**Issue by practiceqian** [alibaba/flutter-go#196]
安装之后比github上的版本少了一栏，开发者也是个人开发者

**Comment by DeckeDeng** [comment]
@practiceqian 你说的是哪个Appstore？华为吗？

**Comment by practiceqian** [comment]
苹果应用商店

**Comment by DeckeDeng** [comment]
@practiceqian 感谢你的提醒，我们目前没有发布到appStore，貌似有个同学发布上去了～好尴尬呀。。代码本来就是开源到
