### ISSUE TITLE
安卓，IOS“组件”栏目白屏

### ISSUE THREAD

**Issue by censhine** [alibaba/flutter-go#2]
安卓，IOS 在点“组件”时白屏，什么都没有，没有案例中的效果

**Comment by hanxu317317** [comment]
因为初始化数据库的过程 . 出现了问题. 导致报错. 已经修复了在最新的master代码.

**Comment by hanxu317317** [comment]
> 安卓，IOS 在点“组件”时白屏，什么都没有，没有案例中的效果

因为初始化数据库的过程 . 出现了问题. 导致报错. 已经修复了在最新的master代码.

**Comment by maofan4041** [comment]
下拉最新的master代码还是白屏

**Comment by kurisu994** [comment]
附议 我的也是白屏 主页都好好的

**Comment by hanxu317317** [comment]
> 下拉最新的master代码还是白屏
给出一下报错信息看看?

**Comment by Nealyang** [comment]
@kurisu994 @maofan4041 本地Flutter版本号多少？

**Comment by kurisu994** [comment]
@Nealyang 

Flutter 1.0.0 
Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

**Comment by kurisu994** [comment]
@hanxu317317 

E/SQLiteLog(  638): (1) no such table: cat
E/flutter (  638): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (  638): DatabaseException(no such table: cat (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM cat WHERE  depth = 1 and parentId = 0) sql 'SELECT * FROM cat WHERE  depth = 1 and parentId = 0' args []}
E/flutter (  638): #0      wrapDatabaseException (package:sqflite/src/exception.dart:125:7)

**Comment by Nealyang** [comment]
@kurisu994 代码已更新，现在Android 模拟器上还有问题么

**Comment by kurisu994** [comment]
@Nealyang  嗯，现在好了
