### ISSUE TITLE
个别路由跳转错误

### ISSUE THREAD

**Issue by simplezhli** [alibaba/flutter-go#202]
我看了一下获取目标组件路由的代码，是一个匹配`targetName` 的for循环，所以数据库中重名的widget name就会跳转到组件列表中最后一个匹配组件的页面。比如下面这个：

![image](https://user-images.githubusercontent.com/12456431/57205540-e3bb1180-6ff1-11e9-93cb-a24b7c0aecab.png)

我还发现重名的两个，不涉及跳转问题，可能只是分类原因。

![image](https://user-images.githubusercontent.com/12456431/57205504-b0788280-6ff1-11e9-921b-5d5e01c900aa.png)

![image](https://user-images.githubusercontent.com/12456431/57205546-efa6d380-6ff1-11e9-99ec-a8bcdc8b4d30.png)

**Comment by ryan730** [comment]
thanks, 会处理一下

**Comment by simplezhli** [comment]
好的
