### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by Panseng** [alibaba/flutter-go#207]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  D:\code\Flutter\flutter-go-master\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  D:\code\Flutter\flutter-go-master\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  D:\code\Flutter\flutter-go-master\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:869: error: resource android:attr/fontVariationSettings not found.
  D:\code\Flutter\flutter-go-master\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:869: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\admin\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-4818971-windows.jar\0a5872f7f50f65f20bcdb2bcdfacb63b\aapt2-3.2.0-4818971-windows\aapt2.exe link -I\
          D:\android\Sdk\platforms\android-27\android.jar\
          --manifest\
          D:\code\Flutter\flutter-go-master\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\code\Flutter\flutter-go-master\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\code\Flutter\flutter-go-master\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\code\Flutter\flutter-go-master\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.ali.fluttergo\
          -0\
          apk\
          --output-text-symbols\
          D:\code\Flutter\flutter-go-master\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.0-4818971-windows Daemon #0
  Output:  C:\Users\admin\.gradle\caches\transforms-1\files-1.1\appcompat-1.0.0.aar\18b0385e7303bbcdc9ffad7c6fc8d568\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

  D:\code\Flutter\flutter-go-master\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.

  C:\Users\admin\.gradle\caches\transforms-1\files-1.1\core-1.0.0.aar\1cf617d21e91aa26a9efcfedcb732637\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\admin\.gradle\caches\transforms-1\files-1.1\core-1.0.0.aar\1cf617d21e91aa26a9efcfedcb732637\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: C:\Users\admin\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-4818971-windows.jar\0a5872f7f50f65f20bcdb2bcdfacb63b\aapt2-3.2.0-4818971-windows\aapt2.exe link -I\
          D:\android\Sdk\platforms\android-27\android.jar\
          --manifest\
          D:\code\Flutter\flutter-go-master\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\code\Flutter\flutter-go-master\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\code\Flutter\flutter-go-master\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\code\Flutter\flutter-go-master\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.ali.fluttergo\
          -0\
          apk\
          --output-text-symbols\
          D:\code\Flutter\flutter-go-master\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.0-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by xavieryang2011** [comment]
同问

**Comment by DeckeDeng** [comment]
@Panseng @xavieryang2011  
Please try this command：
--  flutter pub pub cache repair
--  flutter run

**Comment by simplezhli** [comment]
@Panseng @xavieryang2011 你们的问题和我一样，是不是升级flutter到1.5.4了。问题主要是webview的三方依赖使用的compilesdkversion为28 ，改成27  就好了，我最后还将它依赖的androidx换掉了。

**Comment by Panseng** [comment]
> @Panseng @xavieryang2011
> Please try this command：
> -- flutter pub pub cache repair
> -- flutter run

i have tried to do this way.
it didn't work. still report an error

**Comment by Panseng** [comment]
> @Panseng @xavieryang2011 你们的问题和我一样，是不是升级flutter到1.5.4了。问题主要是webview的三方依赖使用的compilesdkversion为28 ，改成27 就好了，我最后还将它依赖的androidx换掉了。

我尝试过这个方法，同时还有[Flutter应用程序的AndroidX兼容性](https://blog.csdn.net/ocean20/article/details/89215290) 这个方案，均以失败告终
但是同一项目（flutter-go），在另一台电脑通过github desktop下载的不会出现这个问题。

**Comment by simplezhli** [comment]
@Panseng 具体就不清楚了，我改了这里就好了。
![image](https://user-images.githubusercontent.com/12456431/57419301-215cac00-7237-11e9-8b43-b5339c399c66.png)

**Comment by shaohui93** [comment]
请问一下你解决这个问题了吗？

**Comment by DeckeDeng** [comment]
@shaohui93 为了兼容androidX做了一些修改，可以参考一下https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by zcys12173** [comment]
同样遇到这个问题

**Comment by ChickenChan** [comment]
我也碰到这个问题了   用楼上的方法都无法解决   是最新的androidx兼容的问题吗

**Comment by bjxiaowanzi** [comment]
我也一样，试了以上方法，还是没解决

**Comment by WangMiaoGit** [comment]
试过了迁移，但是没有用还是跑不起来

**Comment by xavieryang2011** [comment]
pubspec.yaml文件修改： flutter_webview_plugin: ^0.2.0
就可以了。参考：https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#avoiding-androidx

**Comment by jishutuan** [comment]
@xavieryang2011 亲测有效，已解决。谢谢。 flutter 1.5.4

**Comment by hiquanta** [comment]
不能跑通啊

**Comment by WangMiaoGit** [comment]
> 不能跑通啊

楼上大哥得方法可以，试过了，可以跑啊。

**Comment by BearyWoo** [comment]
把flutter_webview_plugin版本改为 ^0.2.0就可以了

**Comment by sunwgit** [comment]
我这边把代码中所有 `Crashlytics SDK` 注释下的代码都注释掉，然后把 `flutter_webview_plugin: ^0.2.0` 可以跑了

**Comment by hiquanta** [comment]
可以了 我bin cache 下的缓存全部删掉后 能跑通了

**Comment by shaohui93** [comment]
把flutter_webview_plugin版本改为 ^0.2.0 可以编译运行，但是点击list的条目进入详情就报错了。 @BearyWoo

**Comment by renleng** [comment]
确实，把flutter_webview_plugin版本改为 ^0.2.0就可以了
