### ISSUE TITLE
AndroidX问题。

### ISSUE THREAD

**Issue by shaohui93** [alibaba/flutter-go#210]
你好，我把gradle改成gradle-5.1.1-all.zip 然后安装到Android手机上就会编译不过。请问一下这个是什么问题。
Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
         *********************************************************
WARNING: This version of firebase_analytics will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by DeckeDeng** [comment]
@shaohui93  This version of firebase_analytics will break your Android build if it or its dependencies aren't compatible with AndroidX.
这里有提示呢～  你可以修改firebase_analytics版本来解决

**Comment by MeteorStart** [comment]
我也碰到了这个问题 拉下来的代码无法运行

**Comment by itlws** [comment]
我把版本改成最新版本，为什么还是不行呢？
