### ISSUE TITLE
建议升级支持AndroidX

### ISSUE THREAD

**Issue by unreal0** [alibaba/flutter-go#243]
* 建议升级支持AndroidX,每次pull都手动修改.
下面是修改的内容:

  image_picker: ^0.6.0+9
ext.kotlin_version = '1.3.0'
classpath 'com.android.tools.build:gradle:3.3.0'

android.enableJetifier=true
android.useAndroidX=true

compileSdkVersion 28
testInstrumentationRunner "android.test.runner.AndroidJUnitRunner"
androidTestImplementation 'com.android.support.test:runner:1.1.1'
androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.1.1'

**Comment by passioncsu** [comment]
哥们 你提个pr不好嘛

**Comment by DeckeDeng** [comment]
@unreal0 已合并添加过的版本
