### ISSUE TITLE
iOS 没有业界动态

### ISSUE THREAD

**Issue by yunxianglong** [alibaba/flutter-go#252]

**Comment by overlord1126** [comment]
同样, 后来解决了吗?

**Comment by DeckeDeng** [comment]
@yunxianglong @yunxianglong ios由于上线原因注掉了第三方数据tab，同学可以拉代码改一下就可以了哈～

**Comment by overlord1126** [comment]
> @yunxianglong @yunxianglong ios由于上线原因注掉了第三方数据tab，同学可以拉代码改一下就可以了哈～

那确定下 , 就是 从 appStore 下载的版本 是没有'业界动态' tab 的吧

**Comment by DeckeDeng** [comment]
@overlord1126 是的，这个tab是为了帮助大家学习在网上获取的文章，为了避免不必要的麻烦去掉上线的，代码只是注掉了，自学过程中可以自己跑代码学习，灵活学习😄～
