### ISSUE TITLE
能否增加 desktop 的支持

### ISSUE THREAD

**Issue by wangyun** [alibaba/flutter-go#260]
flutter的默认项目我用 https://github.com/google/flutter-desktop-embedding 可以在linux上跑起来，但这个项目还不行，显示的异常是：

[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      invokeMethod (package:sqflite/src/sqflite_impl.dart:18:34)
<asynchronous suspension>
#2      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:33:7)
#3      _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite/src/factory_mixin.dart:22:35)
#4      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:34)
<asynchronous suspension>
#5      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:29:7)
#6      _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite/src/factory_mixin.dart:22:7)
#7      _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite/src/factory_mixin.dart:136:17)
<asynchronous suspension>
#8      getDatabasesPath (package:sqflite/sqflite.dart:162:54)
#9      Provider.init (package:flutter_go/utils/provider.dart:62:34)
<asynchronous suspension>
#10     main (package:flutter_go/main.dart:131:18)
<asynchronous suspension>
#11     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216:25)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208:5)
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by hanxu317317** [comment]
您使用的futter 版本. dart版本最后扔出来一下.  因为flutter一直在更新. 高版本的的接口. 在低版本的flutter环境是不能跑的.

**Comment by wangyun** [comment]
flutter --version 的结果是：

Flutter 1.7.8 • channel dev • https://github.com/flutter/flutter.git
Framework • revision d51fd86cdb (2 天前) • 2019-06-21 22:31:55 -0400
Engine • revision d004bcd4d6
Tools • Dart 2.4.0

**Comment by hanxu317317** [comment]
这个貌似不是我们项目的问题. 是依赖包的问题: 
参考一下: https://github.com/tekartik/sqflite/issues/37

**Comment by wangyun** [comment]
看了下这个包，似乎只提到支持ios和android，估计我应该去他们那里提一下linux的支持了

**Comment by hanxu317317** [comment]
我没有在linux上开发. 不太明白. 在linux跑的不也是android的虚拟机么?

**Comment by wangyun** [comment]
不是的，是让flutter程序直接在linux，windwos，macos上面跑，不需要虚拟机的，你可以看看 https://github.com/google/flutter-desktop-embedding 这个项目

**Comment by hanxu317317** [comment]
还能这样玩?  可以的. 能分享一下, 这个玩法的应用场景是怎么样的么?

**Comment by ryan730** [comment]
如果要跑 flutter-go 在桌面版，需要删除不支持的依赖包，不能编译。。。

**Comment by wangyun** [comment]
就是打算写点简单的桌面应用，现在跨平台的方案要么太老太复杂比如qt，gtk之类，要么太慢太大，比如electron这种，而flutter又小又简单

**Comment by wangyun** [comment]
恩，应该就是插件还不支持其他平台，技术上问题应该不大，只是flutter写桌面应用现在还比较小众吧，插件支持desktop的少

**Comment by hanxu317317** [comment]
感觉以后会有if (ios) if(qilin)  if (Android) if (desktop)   else...这种的判断
