### ISSUE TITLE
main.dart的showWelcomePage方法里明明return的是AppPage(),没搞懂展示了几秒钟的欢迎页是在哪配置的

### ISSUE THREAD

**Issue by dengzhao7053** [alibaba/flutter-go#266]
看了几遍没看懂这，麻烦解答一下谢谢大佬们

**Comment by DeckeDeng** [comment]
@dengzhao7053   在ios和Android项目里面配置
![image](https://user-images.githubusercontent.com/15521823/60476678-0d6d7d80-9caf-11e9-80fb-e5ecb9e8c9d2.png)

**Comment by dengzhao7053** [comment]
谢谢大佬  这样配置的话 欢迎页显示的时间如何控制呢

**Comment by DwayneZhang** [comment]
@dengzhao7053 官方文档有提到过怎么配置启动页，没具体提及控制启动页时间。但文档有提到 runApp绘制第一帧开始，启动页消失。换言之，如果在runApp加延时，是可以变相控制时间的

**Comment by dengzhao7053** [comment]
谢谢大佬们
