### ISSUE TITLE
刚拉取的代码，运行报错

### ISSUE THREAD

**Issue by xyy0725** [alibaba/flutter-go#268]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 1 column 769 path $[4].name

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Finished with error: Gradle task assembleDebug failed with exit code 1

开发环境：
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.14393], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] Connected device (1 available)

**Comment by DeckeDeng** [comment]
@xyy0725 同学可以看看这个(https://github.com/flutter/flutter/issues/25271)

**Comment by xyy0725** [comment]
@DeckeDeng 感谢，我刚在 [https://blog.csdn.net/qq_28115285/article/details/89445461](url)找到了答案。
小白刚进来，解决了这问题 又来了一个。[笑哭]
