### ISSUE TITLE
刚拉的master代码，报错

### ISSUE THREAD

**Issue by yuan9034** [alibaba/flutter-go#269]
E/AndroidRuntime(24310): FATAL EXCEPTION: main
E/AndroidRuntime(24310): Process: com.alibaba.fluttergo, PID: 24310
E/AndroidRuntime(24310): java.lang.OutOfMemoryError: Failed to allocate a 74649612 byte allocation with 16777120 free bytes and 54MB until OOM

**Comment by yuan9034** [comment]
Flutter (Channel stable, v1.5.4-hotfix.2) Android Studio (version 3.4)

**Comment by yuan9034** [comment]
低端手机会oom，换了手机没问题

**Comment by hanxu317317** [comment]
@yuan9034 这个低端机. 是什么手机. 可以把型号贴出来.
