### ISSUE TITLE
好多错误

### ISSUE THREAD

**Issue by hxk1224** [alibaba/flutter-go#270]
1，点击Form->Input->TextField 闪退
2，点击Frame->Box->LimitedBox 闪退
基本上没耐心用了，真的是阿里巴巴出品的吗？

**Comment by Przeblysk** [comment]
我这没有问题

**Comment by hanxu317317** [comment]
@hxk1224 这是flutter框架的产物. 我们只是收纳集合. 还有如果闪退频繁的话. 您可以考虑去看看本地环境的版本问题. 大多是环境问题.

**Comment by jelychow** [comment]
@hxk1224 闪退的话其实建议先贴错误日志
