### ISSUE TITLE
【答疑】每个界面里的返回图标是怎么加进去的

### ISSUE THREAD

**Issue by CK875430315** [alibaba/flutter-go#271]
看到收藏，回到首页，菜单等是统一封装到了WidgetDemo这里，但是没有找到返回按钮是怎么添加的

**Comment by hanxu317317** [comment]
返回按钮是AppBar上自带的. 带有默认的返回操作.   你也可以自己控制返回按钮. @CK875430315

**Comment by jelychow** [comment]
@CK875430315  app 入口 theme: ThemeData()里面可以配置属性
