### ISSUE TITLE
Windows 克隆之后 Checkout 失败（带*的文件）

### ISSUE THREAD

**Issue by upupming** [alibaba/flutter-go#272]
Windows 不支持带 `*` 的文件，克隆之后无法正常 Checkout，请及时修复，谢谢。

![image](https://user-images.githubusercontent.com/24741764/60666694-3867f500-9e9a-11e9-9cc3-2402a22d76bf.png)

**Comment by SteinOboro** [comment]
同上 ，除此之外编译运行失败，报错如下：
`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
ע: C:\Users\Stein\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\firebase_analytics-1.2.0+1\android\src\main\java\io\flutter\plugins\firebaseanalytics\FirebaseAnalyticsPlugin.javaʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
ע: C:\Users\Stein\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\firebase_core-0.3.4\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.javaʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: C:\Users\Stein\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\flutter_webview_plugin-0.3.5\android\src\main\java\com\flutter_webview_plugin\WebviewManager.javaʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
ע: C:\Users\Stein\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\package_info-0.4.0+4\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
Built build\app\outputs\apk\debug\app-debug.apk.
cmd: Can't find service: activity
Installing build\app\outputs\apk\app.apk...
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install F:\flutter\flutter-go-master\build\app\outputs\apk\app.apk: cmd: Can't find service: package
Error launching application on Android SDK built for x86.
`

**Comment by jp1017** [comment]
同样问题

**Comment by hanxu317317** [comment]
这块对windows的确是不太友好.

**Comment by hanxu317317** [comment]
试试不checkout分支 直接clone能不能下载下来
```
git clone -b tagetBranch
```

**Comment by upupming** [comment]
@hanxu317317 其实对于 Windows 来说，Checkout 失败也只是那几个 iOS 的文件失败，其他文件正常，还是可以编译成功的。

**Comment by upupming** [comment]
不修改也没问题 😅 ，建议还是修改一下文件名。

**Comment by jili02** [comment]
同样的问题，在windows下创建不了这几个文件

**Comment by upupming** [comment]
Closing due to no response.
