### ISSUE TITLE
数据库cat 数据是怎么写入的

### ISSUE THREAD

**Issue by JiangYi1993** [alibaba/flutter-go#273]
看源码 没有找到插入cat表格数据的地方，希望指导一下

**Comment by hanxu317317** [comment]
我们是通过sqliteStudio ide 本地跑起来的. 您是打算向我们的组件说明里.提交自己的数据么?

**Comment by JiangYi1993** [comment]
是的，如果我要是想插入数据的话要怎么做，我看创建表 是注释掉了，然后也没有创建数据的操作，只要查询

**Comment by JiangYi1993** [comment]
> 我们是通过sqliteStudio ide 本地跑起来的. 您是打算向我们的组件说明里.提交自己的数据么?

是的，如果我要是想插入数据的话要怎么做，我看创建表 是注释掉了，然后也没有创建数据的操作，只有查询

**Comment by DeckeDeng** [comment]
@JiangYi1993 我们现在正在完善，很快就会有详细的共建文档了，稍微等等哈～
