### ISSUE TITLE
ios版本 一直停留在启动页

### ISSUE THREAD

**Issue by oiar** [alibaba/flutter-go#289]
Failed to find assets path for "Frameworks/App.framework/flutter_assets"
registrationID获取失败，code：1011
![屏幕快照 2019-07-31 上午8 48 53](https://user-images.githubusercontent.com/44365441/62175494-8b857880-b370-11e9-86dd-9c7c59505889.png)
![屏幕快照 2019-07-31 上午8 50 38](https://user-images.githubusercontent.com/44365441/62175503-90e2c300-b370-11e9-8c89-c677a52a4bb6.png)
![屏幕快照 2019-07-31 上午8 44 51](https://user-images.githubusercontent.com/44365441/62175508-93ddb380-b370-11e9-887c-df93d884102f.png)

**Comment by weian123zhang** [comment]
我也是

**Comment by hanxu317317** [comment]
把flutter doctor的信息贴出来. 还有是哪个分支的代码?

### 您当前的flutter doctor信息

### 预期的表现

### 实际的表现

### 预期的分析 (给出您能想到, 任何您能想到的)

### 重现的方式, 例如从 A界面 点击 b, 跳转到B页面, 界面出现溢出乱码等.

### 用于重现此问题或者可能解决以上问题的示例代码（例如github 链接代码)

**Comment by oiar** [comment]
flutter doctor信息：
![image](https://user-images.githubusercontent.com/44365441/62183487-f8a70700-b38c-11e9-8f43-7abe394e69c7.png)
预期表现：
能够进入flutter-go内部页面，而不是一直停留启动页
实际表现：
一直停留在启动页

**Comment by mxpazyj** [comment]
主要是因为`flutter-go.alibaba.net`这个域名的问题
可以先把`main.dart`中192-195行注释解决跳不过去的问题

**Comment by oiar** [comment]
> 主要是因为`flutter-go.alibaba.net`这个域名的问题
> 可以先把`main.dart`中192-195行注释解决跳不过去的问题

您好，我跟从您的建议尝试了一下，结果并没有改变，还是一直停留在启动页

**Comment by oiar** [comment]
flutter run的结果如下：
![image](https://user-images.githubusercontent.com/44365441/62185266-525eff80-b394-11e9-8b8b-20cce1a48c65.png)

**Comment by zpswz** [comment]
确实是域名问题访问不了，不知道作者是否有可访问的域名可以替换

**Comment by zpswz** [comment]
将URL http://flutter-go.alibaba.net/ 改为 https://flutter-go.pub/api/ 问题解决

**Comment by hanxu317317** [comment]
@oiar 已经做了处理. 请拉取最新master分之代码.

**Comment by oiar** [comment]
> @oiar 已经做了处理. 请拉取最新master分之代码.

![image](https://user-images.githubusercontent.com/44365441/62206914-6838e880-b3c5-11e9-962a-3b29a99d7e56.png)

没有更新啊？

**Comment by hanxu317317** [comment]
我们把master回滚了. 今天不小心把我们测试中的分之代码混进了master.
```
git fetch origin master
git checkout -b FETCH_HEAD
git branch -D master
git chekcout -b master
```

**Comment by oiar** [comment]
> 将URL http://flutter-go.alibaba.net/ 改为 https://flutter-go.pub/api/ 问题解决

您好，我尝试了您的方法，仍然不可行

**Comment by oiar** [comment]
> 我们把master回滚了. 今天不小心把我们测试中的分之代码混进了master. @oiar
> 
> ```
> git fetch origin master
> git checkout -b FETCH_HEAD
> git branch -D master
> git chekcout -b master
> ```

您好，我按照指示操作后运行flutter run出现报错：
![屏幕快照 2019-07-31 下午8 24 22](https://user-images.githubusercontent.com/44365441/62211502-3ded2800-b3d1-11e9-983c-3e2c64a5a4cd.png)

**Comment by oiar** [comment]
> 我们把master回滚了. 今天不小心把我们测试中的分之代码混进了master. @oiar
> 
> ```
> git fetch origin master
> git checkout -b FETCH_HEAD
> git branch -D master
> git chekcout -b master
> ```
剩余部分报错截图：
![屏幕快照 2019-07-31 下午8 28 35](https://user-images.githubusercontent.com/44365441/62211747-e8fde180-b3d1-11e9-908c-c711b8f3e81a.png)

flutter doctor 如下：
![屏幕快照 2019-07-31 下午8 25 56](https://user-images.githubusercontent.com/44365441/62211592-8a386800-b3d1-11e9-98e9-5f22950d8e16.png)

**Comment by hanxu317317** [comment]
还是怀疑您的代码没有与master同步. 能看一下您的git log 么?

**Comment by oiar** [comment]
> @oiar 已经做了处理. 请拉取最新master分之代码.



> @oiar 还是怀疑您的代码没有与master同步. 能看一下您的git log 么?

您好，git log如下：
![屏幕快照 2019-08-01 上午11 05 54](https://user-images.githubusercontent.com/44365441/62262787-90b7f580-b44c-11e9-92c7-ef37bea43be0.png)

**Comment by hanxu317317** [comment]
再按
```
git fetch origin master
git checkout -b FETCH_HEAD
git branch -D master
git chekcout -b master

```
保持master分之代码日志是这样
![image](https://user-images.githubusercontent.com/8518989/62263393-9f9fa780-b44e-11e9-9d34-9b3ab07726bd.png)
就可以了.

**Comment by oiar** [comment]
> @oiar
> 再按
> 
> ```
> git fetch origin master
> git checkout -b FETCH_HEAD
> git branch -D master
> git chekcout -b master
> ```
> 
> 保持master分之代码日志是这样
> ![image](https://user-images.githubusercontent.com/8518989/62263393-9f9fa780-b44e-11e9-9d34-9b3ab07726bd.png)
> 就可以了.

Ok! 成功解决了，谢谢大佬。不过您的最后一条指令git chekcout -b master中的checkout打错了。
