### ISSUE TITLE
安装Android 的DemoApp 为什么进来直接白屏。。小米4  手机

### ISSUE THREAD

**Issue by Vander-liu** [alibaba/flutter-go#29]

**Comment by Sky24n** [comment]
同样情况，两个手机都不行
oppo R9 Plusm A   5.1.1
乐视1s  Letv X500   6.0

**Comment by aizya** [comment]
我也是， 红米note4x

**Comment by imlida** [comment]
ios也是

**Comment by hanxu317317** [comment]
@imlida @aizya @Sky24n @Vander-liu 请清除本地缓存后. 拉取最新master代码. 我们已经在master中试图解决兼容的问题. 期待您的反馈.
