### ISSUE TITLE
git pull(win 10) 报错

### ISSUE THREAD

**Issue by bigmonkey1803** [alibaba/flutter-go#290]
![pull error](https://user-images.githubusercontent.com/6063998/62205649-79342a80-b3c2-11e9-9467-4485a6e931a5.JPG)

如上图，网上说是是因为文件命名不适用Windows的规范，要对git做些配置。不知道你们有么有更优雅的解决方式？

谢谢.

**Comment by hanxu317317** [comment]
@bigmonkey1803 我们的master今天不小心合进了beta分支的一些代码.  您可以先回退master分支.  我们看看有什么办法解决git invalid argument的问题

**Comment by hanxu317317** [comment]
可以参考以下方式. 试一下?
https://stackoverflow.com/questions/26097568/git-pull-error-unable-to-create-file-invalid-argument

![image](https://user-images.githubusercontent.com/8518989/62207715-725be680-b3c7-11e9-9b09-b60b5c280129.png)

**Comment by bigmonkey1803** [comment]
> 可以参考以下方式. 试一下?
> https://stackoverflow.com/questions/26097568/git-pull-error-unable-to-create-file-invalid-argument
> 
> ![image](https://user-images.githubusercontent.com/8518989/62207715-725be680-b3c7-11e9-9b09-b60b5c280129.png)

谢谢帮助寻找解决方案，我昨天也看到了类似的贴子。但是我没有尝试这种方式，raised这个issue主要是想看看是否有其他人在Windows 10 下也遇到类似问题，是否是一个普遍的问题。

**Comment by hanxu317317** [comment]
暂时未大量收到反馈. 不过您可以按上边这个方法试一下. 不是很麻烦. 如果可以. 正好您的这个反馈. 可以为其他人做参考.

**Comment by bigmonkey1803** [comment]
Hi @hanxu317317 

我刚才抽空试了一下stackoverflow上的这个方法。首先，可以pull了，看起来很正常。但是问题来了，ios/Runner/Assets.xcassets/AppIcon.appiconset文件夹不见了：
![image](https://user-images.githubusercontent.com/6063998/62285223-c5956e00-b487-11e9-80e7-1eba07f1dcab.png)

![image](https://user-images.githubusercontent.com/6063998/62285185-b2829e00-b487-11e9-9127-06dc4dc12408.png)

也就是说在.git/info/sparse-checkout下添加：
*
!ios/Runner/Assets.xcassets/AppIcon.appiconset/*
就以为这不去拉这个目录。“!”就是排除这个目录嘛。

如果有人在Win10下遇到这种问题并已完美解决，请指点下，多谢。

**Comment by prczhb** [comment]
> @bigmonkey1803 我们的master今天不小心合进了beta分支的一些代码. 您可以先回退master分支. 我们看看有什么办法解决git invalid argument的问题

能不能删掉Git记录 就是不删文件的那种 新建一个分支 或者删掉那个记录 要不然所有的Windows用户全完了 不能git ,只能下载master.Zip这种形式了 但是这样版本切换就是废了

**Comment by TobiasYin** [comment]
clone 下来就报同样的错了

**Comment by RookieApe** [comment]
期待早日解决

**Comment by longting** [comment]
windows操作系统上clone存在此问题

**Comment by kaisawind** [comment]
#344

**Comment by hanxu317317** [comment]
该问题已经解决. 请拉取最新的master代码.
