### ISSUE TITLE
小米Mix3 中间WIDGET 页面白屏，内容无法显示

### ISSUE THREAD

**Issue by Ava07** [alibaba/flutter-go#291]
小米Mix3 中间WIDGET 页面白屏，内容无法显示

**Comment by hanxu317317** [comment]
@Ava07  
小米mix3下.的确容易复现这个问题. 我们正在把本地数据变为服务端数据. 正在解决中. 下一个版本. 会修复这个兼容性问题.

**Comment by Ava07** [comment]
下一个版本什么时候上呢，好捉急。

**Comment by hanxu317317** [comment]
快到了~莫急~~ 我们现在人手不足. 只能一点点来

**Comment by Ava07** [comment]
好，我等到起

**Comment by wtus** [comment]
我记得之前没这个问题啊，新下载了，发现同样的问题，  miui 10

**Comment by Ava07** [comment]
> 我记得之前没这个问题啊，新下载了，发现同样的问题， miui 10

下一个版本快了

**Comment by xurui1995** [comment]
一加5T同样空白

**Comment by hanxu317317** [comment]
新版本已经解决. @Ava07 @wtus
