### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Sky24n** [alibaba/flutter-go#30]
Launching lib/main.dart on Letv X500 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/4.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/5.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/6.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/7.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/8.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/9.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/10.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/11.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/12.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/13.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/14.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/15.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/16.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/17.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/18.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/19.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/20.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/21.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/22.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/23.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/24.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/25.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/26.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/27.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/28.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/29.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/30.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/31.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/32.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/33.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/34.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/35.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/36.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/37.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/38.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/39.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/40.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/41.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/42.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/43.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/44.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/45.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/46.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/47.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/48.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/49.jar, /Users/thl/AndroidStudioProjects/demo workspace/flutter-go/build/app/intermediates/transforms/dexBuilder/debug/50.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by guoruin123** [comment]
遇到相同的错误

**Comment by hanxu317317** [comment]
参考 flutter https://github.com/flutter/flutter/issues/26445
感觉有可能是同一类问题导致.

**Comment by JSnail** [comment]
> 参考 flutter [flutter/flutter#26445](https://github.com/flutter/flutter/issues/26445)
> 感觉有可能是同一类问题导致.

nice 兄嘚 我去掉fluttertoast 的^就编译通过了

**Comment by hanxu317317** [comment]
> > 参考 flutter [flutter/flutter#26445](https://github.com/flutter/flutter/issues/26445)
> > 感觉有可能是同一类问题导致.
> 
> nice 兄嘚 我去掉fluttertoast 的^就编译通过了

兄嘚~你试试把fluttertoast版本号改成2.2.6试一下? 看看报错不?

**Comment by Sky24n** [comment]
确实是fluttertoast的锅，改了就可以了

**Comment by hanxu317317** [comment]
请清除本地缓存后. 拉取最新master代码. 我们已经在master中试图解决兼容的问题. 期待您的反馈.

**Comment by DarrenKong** [comment]
> 请清除本地缓存后. 拉取最新master代码. 我们已经在master中试图解决兼容的问题. 期待您的反馈.

对于fluttertoast，它最近升级到SDK 28 [(fluttertoast commits)](https://github.com/PonnamKarthik/FlutterToast/commits/master)
可以临时删除yaml中fluttertoast的^来解决这个的问题。
`fluttertoast: 2.2.3`
