### ISSUE TITLE
登录错误

### ISSUE THREAD

**Issue by Peroluo** [alibaba/flutter-go#316]
虚拟机调试登录不成功

**Comment by Nealyang** [comment]
用的哪种方式登录？github oAuth？还是账号密码？界面是否有弹出错误信息？

**Comment by Peroluo** [comment]
http://flutter-go.alibaba.net/





------------------ 原始邮件 ------------------
发件人: "一凨"<notifications@github.com>; 
发送时间: 2019年8月21日(星期三) 上午10:45
收件人: "alibaba/flutter-go"<flutter-go@noreply.github.com>; 
抄送: "pero"<1025558554@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alibaba/flutter-go] 登录错误 (#316)




用的哪种方式登录？github oAuth？还是账号密码？界面是否有弹出错误信息？

**Comment by Peroluo** [comment]
------------------ 原始邮件 ------------------
发件人: "一凨"<notifications@github.com>; 
发送时间: 2019年8月21日(星期三) 上午10:45
收件人: "alibaba/flutter-go"<flutter-go@noreply.github.com>; 
抄送: "pero"<1025558554@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alibaba/flutter-go] 登录错误 (#316)




用的哪种方式登录？github oAuth？还是账号密码？界面是否有弹出错误信息？

**Comment by Nealyang** [comment]
> ------------------ 原始邮件 ------------------ 发件人: "一凨"<notifications@github.com>; 发送时间: 2019年8月21日(星期三) 上午10:45 收件人: "alibaba/flutter-go"<flutter-go@noreply.github.com>; 抄送: "pero"<1025558554@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [alibaba/flutter-go] 登录错误 (#316) 用的哪种方式登录？github oAuth？还是账号密码？界面是否有弹出错误信息？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

地址已经修改了，应该登陆没问题了
