### ISSUE TITLE
发现Flutter最新的1.9.x版本构建正式发布包合成了libapp.so

### ISSUE THREAD

**Issue by liyujiang-gzu** [alibaba/flutter-go#325]
发现Flutter最新的1.9.x版本构建正式发布包变化了。FlutterGo v1.0正式包的isolate_snapshot_data等核心文件还是放在包内的assets目录下，而1.9.x版本构建的正式发布包已经没有isolate_snapshot_data等文件，貌似谷歌暂停了热更新的开发，AOT编译直接生成so文件了，取代的是合成【libapp.so】和libflutter.so一起放在lib目录下，感觉更加高大上。

**Comment by hanxu317317** [comment]
> 貌似谷歌暂停了热更新的开发
这句话是错的. 他们已经决定停止了.
