### ISSUE TITLE
各位大神，请问有什么方法可以在app图标上显示消息数量？

### ISSUE THREAD

**Issue by hzbsccd** [alibaba/flutter-go#339]
最近用flutter开发了一个带即时通的功能，想了很多办法查找，都没有找到可以针对flutter，让消息数量显示到app右上角的解决方案。
请问有哪位大神可以指点一二，或者给个思路，不胜感激……

**Comment by hanxu317317** [comment]
@hzbsccd  在这个仓库下有很多有用的工具 [Badger](https://github.com/g123k/flutter_app_badger) 这个工具可以满足你的需求.

**Comment by hzbsccd** [comment]
@hanxu317317 虽然还没有试，但是初步感觉是很不错的解决方案。真的是非常感谢！

**Comment by hanxu317317** [comment]
其实就是调用 的flutter 的sevice可以看一下源码.很简单.
