### ISSUE TITLE
项目内的IOS的图片命名含“*”无法在Windows系统上存储

### ISSUE THREAD

**Issue by chaunqingren** [alibaba/flutter-go#344]
## Bug Report
项目内的IOS的图片命名含“*”无法在Windows系统上存储，不能clone ios的图片资源。
```
error: unable to create file ios/Runner/Assets.xcassets/AppIcon.appiconset/1024*1024@as.png: Invalid argument
```

**Comment by charliezzo** [comment]
![image](https://user-images.githubusercontent.com/9925064/64099381-b7df4b00-cd9b-11e9-9910-45d1405067c8.png)

**Comment by liyujiang-gzu** [comment]
“*”不是应该用“x”的吗

**Comment by hanxu317317** [comment]
这个是文件系统的问题

**Comment by liyujiang-gzu** [comment]
> 这个是文件系统的问题

我的意思是，能不能把文件名用“x”代替“*”，可以同时兼顾Mac/Linux及Windows用户

**Comment by kaisawind** [comment]
需要有人提交一下PR，由于`*`特殊字符的原因，导致git冲突无法解决，所以无法提交PR。

**Comment by hanxu317317** [comment]
关于windows下图片的问题, 已经解决. 欢迎大家拉取最新的代码
@chaunqingren @charliezzo @liyujiang-gzu
