### ISSUE TITLE
Android版本卡在启动页

### ISSUE THREAD

**Issue by TheStar4Fate** [alibaba/flutter-go#348]
## Bug Report

看了#289，尝试了里面提到的方法，APP仍然无法正常运行

### 您当前的flutter doctor信息
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.5.9-pre.171, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.1.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.37.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

### 预期的表现
能正常进入APP

### 实际的表现
卡在启动页，不能进入APP

### 预期的分析 
无法获取配置信息

### 重现的方式 
使用Android Stuido运行，Run中显示如下信息

Launching lib/main.dart on vivo NEX A in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
D/FlutterJPushPlugin(30028): register jpush plugin
E/flutter (30028): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (30028): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (30028): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (30028): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:73:7)
E/flutter (30028): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
E/flutter (30028): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter (30028): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
E/flutter (30028): <asynchronous suspension>
E/flutter (30028): #4      invokeMethod (package:sqflite/src/sqflite_impl.dart:18:34)
E/flutter (30028): <asynchronous suspension>
E/flutter (30028): #5      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:33:7)
E/flutter (30028): #6      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite/src/factory_mixin.dart:22:35)
E/flutter (30028): #7      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:34)
E/flutter (30028): <asynchronous suspension>
E/flutter (30028): #8      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:29:7)
E/flutter (30028): #9      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite/src/factory_mixin.dart:22:7)
E/flutter (30028): #10     SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite/src/factory_mixin.dart:136:17)
E/flutter (30028): <asynchronous suspension>
E/flutter (30028): #11     getDatabasesPath (package:sqflite/sqflite.dart:166:54)
E/flutter (30028): #12     Provider.init (package:flutter_go/utils/provider.dart:62:34)
E/flutter (30028): <asynchronous suspension>
E/flutter (30028): #13     main (package:flutter_go/main.dart:207:18)
E/flutter (30028): <asynchronous suspension>
E/flutter (30028): #14     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
E/flutter (30028): #15     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (30028): #16     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (30028): #17     _runZoned (dart:async/zone.dart:1516:10)
E/flutter (30028): #18     runZoned (dart:async/zone.dart:1500:12)
E/flutter (30028): #19     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
E/flutter (30028): #20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter (30028): #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter (30028): 
W/ibaba.flutterg(30028): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
Syncing files to device vivo NEX A...
E/FirebaseInstanceId(30028): Google Play services missing or without correct permission.
E/FirebaseInstanceId(30028): Google Play services missing or without correct permission.
E/Fabric  (30028): Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.alibaba.fluttergo/settings
E/Answers (30028): Failed to retrieve settings
W/CrashlyticsCore(30028): Received null settings, skipping report submission!

### 用于重现此问题或者可能解决以上问题的示例代码（例如github 链接代码)
master分支代码

**Comment by zcchongpangzi** [comment]
看下这个https://github.com/flutter/flutter/issues/39620
试试看将 WidgetsFlutterBinding.ensureInitialized() 放在main函数第一行

**Comment by TheStar4Fate** [comment]
> 看下这个[flutter/flutter#39620](https://github.com/flutter/flutter/issues/39620)
> 试试看将 WidgetsFlutterBinding.ensureInitialized() 放在main函数第一行

可以了，谢谢
