### ISSUE TITLE
github授权登录不了

### ISSUE THREAD

**Issue by evansherry** [alibaba/flutter-go#357]
## Bug Report

**仅限中文与英文**, 其他语言的提交将直接被关闭

请先确认查找了已有的 issue [GitHub issues](https://github.com/apache/incubator-shardingsphere-example/issues).

### 预期的表现
正常登录

### 实际的表现
github授权页面授权按钮复发点击，右侧arrow点击没反应。首页输入github账号密码无效，应该是授权没成功

### 预期的分析 (给出您能想到, 任何您能想到的)
授权通过，并登录成功

**Comment by hanxu317317** [comment]
收到您的反馈. 初步怀疑是github在国内偶尔被墙的原因. 我们也会跟进.

**Comment by zcchongpangzi** [comment]
登录页面点击没反应是login_page 140,183有问题，返回值改为null就好了,validator返回值为null才表示成功。。可能是这个原因

**Comment by evansherry** [comment]
@zcchongpangzi 谢谢，跟了下代码根据validator是否为null判断的（hasError => _errorText != null）。
@hanxu317317
