### ISSUE TITLE
flutter如何打开 淘宝app，咨询i一下，求各位大神解答

### ISSUE THREAD

**Issue by webkonglong** [alibaba/flutter-go#358]
求问flutter如何打开第三方app,，我想flutter一件打开淘宝app，但是我发现我，我无法打开，我通过搜索引擎拿到的方法都是 url_launcher这个插件，这个插件，好像无法打开淘宝，，，，我目前的做法是  拿到了 手机淘宝app在ios的app Store链接，用url_launcher打开这个链接， 然后会跳转到app Store，app store在一建打开淘宝，，但是安卓我就没辙了，，求大神们，提供一下  flutter如何一键打开淘宝app，

**Comment by logney** [comment]
用url_launcher插件，比如打开高德地图
var isCanLaunch = await canLaunch('androidamap://navisourceApplication=amap&lat=$lat&lon=$lon');
                      if (isCanLaunch != null && isCanLaunch ) {
                        launch(mapUrl);
                      } else {
                        ToastUtil.showToast('请安装第三方地图软件');
                      }

**Comment by webkonglong** [comment]
> 用url_launcher插件，比如打开高德地图
> var isCanLaunch = await canLaunch（'androidamap：// navisourceApplication = amap＆lat = $ lat＆lon = $ lon'）;
> if（isCanLaunch！= null && isCanLaunch）{
> launch（mapUrl）;
> } else {
> ToastUtil.showToast（'请安装第三方地图软件'）;
> }

淘宝呢，如何打开 手机淘宝。

**Comment by hanxu317317** [comment]
@webkonglong 唤起其他应用需要知道其他应用的schema.
类似这样:

- QQ： mqq:// 
- 微信： weixin:// 
- 京东： openapp.jdmoble:// 
- 淘宝： taobao://

**Comment by hanxu317317** [comment]
@webkonglong 参考: https://juejin.im/post/5d80e28a6fb9a06ad005a3c6

**Comment by webkonglong** [comment]
> @webkonglong参考：[https](https://juejin.im/post/5d80e28a6fb9a06ad005a3c6) : //juejin.im/post/5d80e28a6fb9a06ad005a3c6[](https://juejin.im/post/5d80e28a6fb9a06ad005a3c6)

ios机器测试无法打开  代码如下

`_launchURL() async {
    String url ="taobao://item.taobao.com/item.html?id=600484941951";
    print(url);
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }`

**报错如下**

`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Could not launch taobao://item.taobao.com/item.html?id=600484941951
#0      _GoodInfo._launchURL (package:myapp/components/good_info.dart:25:7)
<asynchronous suspension>
#1      _GoodInfo.build.<anonymous closure> (package:myapp/components/good_info.dart:220:15)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
#3      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
#4      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:177:9)
#5      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
#6      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
#7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
#8      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:221:19)
#9      _WidgetsFlutt<…>`

**Comment by webkonglong** [comment]
我手机有装淘宝app但是他检测不到我手机有淘宝app 。await canLaunch(url) 的值 是false ..

**Comment by hanxu317317** [comment]
@webkonglong 
需要去info.plist文件中配置权限.

**Comment by webkonglong** [comment]
我没找到这个文件，，，

**Comment by hanxu317317** [comment]
https://jingyan.baidu.com/article/c85b7a646a79a8003aac955a.html

**Comment by webkonglong** [comment]
谢谢，老哥 感谢。

**Comment by webkonglong** [comment]
老哥 我在多嘴问一下，我们这个打开第三方应用 是需要什么权限呢？

**Comment by webkonglong** [comment]
`_launchURL() async {
    String url ="taobao://";
    await launch(url);
  }`

上面代码就行，

别加 if await canLaunch(url)  判断 ，我去改了权限 await canLaunch(url)  的值一直是false。

**Comment by hanxu317317** [comment]
这是官方的文档. 出于安全的角度, 最好找到问题原因. 不然如果出现用户手机未安装淘宝. 可能会出问题.

**Comment by hanxu317317** [comment]
我之前使用这块也出现过问题. 建议把手机中的APP删除了. 重新运行试试.

**Comment by Maclaon** [comment]
> `_launchURL() async { String url ="taobao://"; await launch(url); }`
> 
> 上面代码就行，
> 
> 别加 if await canLaunch(url) 判断 ，我去改了权限 await canLaunch(url) 的值一直是false。

我想问一下，你这个解决了吗？不管淘宝，微信，智能在app内部打开，但是浏览器就可以打开外部的！

**Comment by klioen** [comment]
请问下，ios里怎么打开app store
