### ISSUE TITLE
go-cli报错

### ISSUE THREAD

**Issue by duxingxia081** [alibaba/flutter-go#385]
build_page_list.dart中package:mustache/mustache.dart找不到
create_demo.dart中package:dart_inquirer/dart_inquirer.dart找不到
create_page.dart中package:dart_inquirer/dart_inquirer.dart找不到
watch_md.dart中package:watcher/watcher.dart找不到
demo.dart中package:console/console.dart找不到

**Comment by hanxu317317** [comment]
暂时go-cli还存放在flutterGo的项目中.  需要单独安装依赖

```
cd go-cli

pub get
```

后期完善一下. 也许会单独抽成独立
