### ISSUE TITLE
flutter for web 有没有方法上传文件（大小30M以上）？

### ISSUE THREAD

**Issue by LISONG040576** [alibaba/flutter-go#388]
各位大神，目前开发flutter web 网页，需要上传比较大的文件，目前知道的方法是：
MultipartFile multipartFile = await MultipartFile.fromFile(filePath);
    FormData formData =
        FormData.fromMap({"files": [multipartFile]});
    print(multipartFile);
    Response response = await dio
        .post("http://********", data: formData);

但是目前遇到两问题：一个是web版本不支持这个上传的方法，另一个是获取不到文件的路径，
请问有什么办法可以正确的上传文件呢？

**Comment by hanxu317317** [comment]
@LISONG040576 dio的代码没有看过. 这个问题应该去dio下的issue提问.  
dio 在 3.0.0中支持了flutter web版. 可以查看具体文档
