### ISSUE TITLE
一开始打开是正常的 重新进以后 点页面任何功能都直接崩溃

### ISSUE THREAD

**Issue by fangkyi03** [alibaba/flutter-go#390]
![image](https://user-images.githubusercontent.com/30390014/67500596-8016c480-f6b5-11e9-8199-e810d716bcb0.png)

**Comment by fangkyi03** [comment]
scrcpy的问题 只要在scrcoy里面点击 点击页面的任何一个按钮 都崩溃 人为操作没问题 你们可以看一下或许能找到意外的bug

**Comment by hanxu317317** [comment]
@fangkyi03 重新打开任意界面点击都报错么?

**Comment by fangkyi03** [comment]
在scrcpy下面 点击页面的任何一个地方都崩溃
