### ISSUE TITLE
github button

### ISSUE THREAD

**Issue by sxy759334746** [alibaba/flutter-go#392]
那个github按钮太靠近屏幕上端，刘海屏的手机点不到

**Comment by hanxu317317** [comment]
有截图么? 哪个界面?

**Comment by sxy759334746** [comment]
就 关于手册 那个界面右上角那个按钮，不会是置灰的吧发自我的华为手机-------- 原始邮件 --------主题：Re: [alibaba/flutter-go] github button (#392)发件人：hanxu317317 收件人：alibaba/flutter-go 抄送：sxy759334746 ,Author 有截图么? 哪个界面?

**Comment by hanxu317317** [comment]
看到了. 那个界面暂时不知道做什么. 先占位. 还是感谢您的反馈.
