### ISSUE TITLE
提供的Android二维码下载不了

### ISSUE THREAD

**Issue by xyhxyw** [alibaba/flutter-go#40]
提供的Android二维码下载不了。请确认下是否链接是否正常。

**Comment by hanxu317317** [comment]
> 提供的Android二维码下载不了。请确认下是否链接是否正常。

亲~国内有时候登陆 github会抽风. 下载地址在release里

**Comment by hanxu317317** [comment]
https://github.com/alibaba/flutter-go/releases

**Comment by fg2q1q3q** [comment]
二维码指向的也是release地址，但是这个地址是真的很差，不管是国内网络还是vpn网络，完全都下载不了，建议上传蒲公英或者蓝奏吧，实在受不了这个死链
