### ISSUE TITLE
Fish-Redux 重构

### ISSUE THREAD

**Issue by YoLoveLife** [alibaba/flutter-go#423]
## Feature Request

**仅限中文与英文**, 其他语言的提交将直接被关闭

请先确认查找了已有的 issue [GitHub issues](https://github.com/apache/incubator-shardingsphere-example/issues).

为了更好的收录您反馈或者提交的相关pr. 请您关注您提交的问题, 我们可能需要更多的详细信息, 我们会在issue下先您收集相关信息,
如果长时间未得到您的回复, 如果我们无法在某些环境上重现该问题, 并且您**超过7天未回复**, 我们可能会关 **闭掉issue**, 谢谢

### 您的功能需求是否与哪些问题有关?
Fish-Redux框架

### 描述您想要的功能.
是否有计划使用开源的Fish-Redux重构Flutter-GO，现在Flutter-GO已经是一个极其适合初学者学习Flutter的APP，但是Flutter-GO的代码内容相对初学者还是较为晦涩，Fish-Redux框架重构Flutter-GO能够进一步降低Flutter使用者的学习门槛。

**Comment by hanxu317317** [comment]
fish redux 闲鱼推的力度很大.  但是重构需要大量的人力. 可能暂时不会考虑.  我们重在内容. 不在于用什么框架写内容. 是吧~~亲~~
