### ISSUE TITLE
请问怎么投稿😄 flutter实现微信7.0UI

### ISSUE THREAD

**Issue by Liberxue** [alibaba/flutter-go#48]
[flutter实现微信7.0UI](https://github.com/Liberxue/xchat ) https://github.com/Liberxue/xchat 目前正在开发中，
![image](https://user-images.githubusercontent.com/5831248/51193915-eef40f80-1924-11e9-8128-4e7009882ad2.png)
![image](https://user-images.githubusercontent.com/5831248/51193922-f4515a00-1924-11e9-83b4-30c471c7cf1e.png)

**Comment by hanxu317317** [comment]
小哥. 这怎么看怎么也就是微信的官方版. 1:1还原啊
小哥想投稿. 是想在把这个加成一个demo. 进入到我们的展示里么?

**Comment by fg2q1q3q** [comment]
@Liberxue 省省吧，这个微信复刻项目难道不是bilibili上的flutter视频教学项目？

**Comment by Liberxue** [comment]
> @Liberxue 省省吧，这个微信复刻项目难道不是bilibili上的flutter视频教学项目？

- 本来打算fork不过，` bilibili`作者写的很多地方不敢雷同，
- 所以我一行一行整了
- 话说大家不都是`复刻`微信？
- 为什么省省！看着`不爽`我就动手自己整，有什么问题？

**Comment by Liberxue** [comment]
> @Liberxue 省省吧，这个微信复刻项目难道不是bilibili上的flutter视频教学项目？

- 本来打算fork不过，` bilibili`作者写的很多地方不敢恭维，
- 所以我一行一行整了。
- 话说大家不都是`复刻`微信？
- 为什么省省！看着`不爽` 我就动手自己整，有什么问题？
---
@fg2q1q3q

**Comment by fg2q1q3q** [comment]
@Liberxue 同学，复刻微信我早几个月前就自己一行一行做过了，让你省省是为了大家好，不要什么demo都去投稿，你是搞技术的，不是卖口活的，不要弄个demo就要往公共库里塞

**Comment by w4ctech** [comment]
> > @Liberxue 省省吧，这个微信复刻项目难道不是bilibili上的flutter视频教学项目？
> 
> * 本来打算fork不过，` bilibili`作者写的很多地方不敢恭维，
> * 所以我一行一行整了。
> * 话说大家不都是`复刻`微信？
> * 为什么省省！看着`不爽` 我就动手自己整，有什么问题？
> 
> @fg2q1q3q

另外 我想问下，为什么Closed了我的issues

**Comment by Liberxue** [comment]
> @w4ctech 这位同学，建议你去b站直接看教学视频吧，虽然up主有些地方写的并不优雅而且自己也不是很熟悉，但是视频质量还是可以的，作为入门级教程还是绰绰有余，最关键的是能让你学习到如何去正确使用api，授人以鱼不如授人以渔，自己看一遍再回头单独写一遍，基本上就入门了



> @w4ctech 这位同学，建议你去b站直接看教学视频吧，虽然up主有些地方写的并不优雅而且自己也不是很熟悉，但是视频质量还是可以的，作为入门级教程还是绰绰有余，最关键的是能让你学习到如何去正确使用api，授人以鱼不如授人以渔，自己看一遍再回头单独写一遍，基本上就入门了

---

> @Liberxue 同学，复刻微信我早几个月前就自己一行一行做过了，让你省省是为了大家好，不要什么demo都去投稿，你是搞技术的，不是卖口活的，不要弄个demo就要往公共库里塞

---

- 虽然up主有些地方写的并不优雅而且自己也不是很熟悉，但是视频质量还是可以的` 
-  让你省省是为了大家好
- 不要什么demo都去投稿
---
- 这里放的不都是demo吗？ 
- 你什么时间写过关我什么事，关大家什么事？
- 自己都不熟悉，是怎么`授人以渔`,如何`授人以渔`? 
- 你要推广专门开一个issues。再见拉黑！
- 最后一句  谢谢，别动不动为大家好！你仅代表`你`而已，别动不动为`大家`！

**Comment by hanxu317317** [comment]
小哥们~我们欢迎大家提任何的issue issuse暂时先关了.  后期我们会开放一个demo专栏. 到时候欢迎大家往脸上甩Demo~ GO GO GO, Coding~

**Comment by hanxu317317** [comment]
@Liberxue 小哥我们的app支持投稿了.   详情可以进群里看下
![image](https://user-images.githubusercontent.com/8518989/63991295-c0c0ea00-cb19-11e9-91b5-1172aa786a18.png)
