### ISSUE TITLE
启动之后报错 Error running pod install 

### ISSUE THREAD

**Issue by victhjy** [alibaba/flutter-go#59]
master 分支
flutter packages get 成功之后运行到 iPhoneXR 模拟器会出现下面的报错信息
`/Users/jinyanghuang/.rvm/gems/ruby-2.3.0@global/bin/pod:23:in `load'
/Users/jinyanghuang/.rvm/gems/ruby-2.3.0@global/bin/pod:23:in `<main>'
Error output from CocoaPods:
↳
WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
Consider adding the following to ~/.profile:
export LANG=en_US.UTF-8
[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
[!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
**Error running pod install
Error launching application on iPhone XR.**
Exited (sigterm)`

我直接在终端给 pod install 会报这个错：
@repo_update
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
no env sources
**[!] Unable to find a specification for `FMDB (~> 2.7.2)` depended upon by `sqflite`**

感觉是我这儿的个例，`sqflite` 里面的  FMDB 找不到，该怎么处理呢

**Comment by LustySwimmer** [comment]
@victhjy cocoapods 的问题，更新到最新的版本就可以了：sudo gem install cocoapods --pre
