### ISSUE TITLE
什么时候才有ios安装包呀？用iphone的表示好想安装来学习

### ISSUE THREAD

**Issue by zhengzejian** [alibaba/flutter-go#83]

**Comment by hanxu317317** [comment]
> _No description provided._

@zhengzejian 小哥~~你如果是mac, 可以xcode直接安装到手机上.  如果是windows,你可以装android模拟器体验.

**Comment by ORACLE128G** [comment]
没有Mac手机却是iphone无解！

**Comment by hanxu317317** [comment]
ios包.我们正在申请. 3月份, 会在商店上架

**Comment by CoderYuri** [comment]
有xcode和iPhone 还是运行不起来

**Comment by CoderYuri** [comment]
pod install 一直有问题

**Comment by CoderYuri** [comment]
@hanxu317317

**Comment by rudian** [comment]
期待有ios安装包

**Comment by SeanZom** [comment]
> 有xcode和iPhone 还是运行不起来

@CoderYuri 你应该使用官方推荐的Editor或者IDE，Xcode是跑不起来的。
Check this link：https://flutter.dev/docs/get-started/test-drive?tab=androidstudio

**Comment by catalsdevelop** [comment]
自己本地编译一下不就可以了，用`flutter run --release`跑起来，注意下codesign问题，其他都是按部就班的把。我再ios11 5s下跑的，没有问题。

**Comment by hanxu317317** [comment]
建议按照官方指引. 一步一步安装执行. 正常都是可以跑起来的.

**Comment by DeckeDeng** [comment]
@rudian @ORACLE128G @zhengzejian IOS版本已上架，亲，自取哈～issues关闭了哟～期待大家可以加入共建多多提pr哈～
