### ISSUE TITLE
命名规范 区分大小写

### ISSUE THREAD

**Issue by tianhongjie** [alibaba/flutter-go#84]
**我再三确认了下, 是_阿里拍卖前端团队_*

这是一个好的项目, 有几个文件未能区分大小写.

有一份 **阿里巴巴Java开发手册** 

所有地方请严格区分大小写, 不然对新人很不友好.

**Comment by surmon-china** [comment]
还有文件结构组织、语法缩进、还有各业务模块的设计和解耦... 我也反复确认了这是 aliababa 的项目，有点伤心

**Comment by champkeh** [comment]
所以，我打算等正式版发布之后再回来看代码

**Comment by hanxu317317** [comment]
- 这是一个业余自发的项目
- 这是非正式版, 目前才发展到0.0.5, 只是用来参考学习
- flutter依赖的dart,而非java. 各自开发规范不尽相同, 
- 我们正在标准化.  java也不是刚出现, 就有标准化的规范.
@tianhongjie @surmon-china @champkeh
